'use client';
import { useState } from 'react';
import Link from 'next/link';
import { talkingDrum } from '@/lib/demo/talking-drum';
import type { GameState } from '@/types/game';

export default function Play(){
 const [state,setState]=useState<GameState>({currentSceneId:'discovery',inventory:[],visited:[]});
 const scene=talkingDrum.scenes.find(s=>s.id===state.currentSceneId)!;
 const choose=(choice:any)=>setState(s=>({...s,currentSceneId:choice.nextSceneId,inventory:choice.givesItemId?[...new Set([...s.inventory,choice.givesItemId])]:s.inventory,visited:[...s.visited,s.currentSceneId]}));
 const ending=scene.id==='truth-ending'||scene.id==='guardian-ending'||scene.id==='guardian';
 return <main className="min-h-screen bg-[#10261b] p-5 text-white"><div className="mx-auto max-w-4xl"><div className="flex items-center justify-between py-5"><Link href="/" className="text-xl font-black">NaijaVerse <span className="text-[#e8c66c]">AI</span></Link><span className="rounded-full bg-white/10 px-3 py-1 text-xs">DEMO MODE</span></div><div className="mb-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-[#e8c66c] transition-all" style={{width:`${Math.min(100,((state.visited.length+1)/6)*100)}%`}}/></div><section className="overflow-hidden rounded-[2rem] bg-[#1b4933] shadow-2xl"><div className="p-8 md:p-12"><p className="text-sm font-bold tracking-widest text-[#e8c66c]">THE TALKING DRUM · ENUGU</p><h1 className="mt-3 text-4xl font-black md:text-6xl">{scene.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/80">{scene.narration}</p>{scene.dialogue&&<div className="mt-8 rounded-2xl border border-white/10 bg-black/10 p-5"><p className="font-bold">{scene.dialogue.speaker}</p><p className="mt-2 text-white/70">“{scene.dialogue.text}”</p></div>}{state.inventory.length>0&&<div className="mt-5 text-sm text-[#e8c66c]">Inventory: {state.inventory.map(id=>talkingDrum.items.find(i=>i.id===id)?.name).join(', ')}</div>}{ending?<div className="mt-10 rounded-2xl bg-white p-6 text-[#10261b]"><p className="text-sm font-bold uppercase tracking-widest text-[#b77b12]">Adventure complete</p><h2 className="mt-2 text-2xl font-black">{scene.title}</h2><p className="mt-2 text-[#56645b]">{scene.narration}</p><button onClick={()=>setState({currentSceneId:'discovery',inventory:[],visited:[]})} className="mt-6 rounded-full bg-[#123d29] px-6 py-3 font-bold text-white">Play Again</button></div>:<><h2 className="mt-10 text-xl font-black">What do you do?</h2><div className="mt-4 grid gap-3">{scene.choices.map(c=><button key={c.id} onClick={()=>choose(c)} disabled={!!c.requiresItemId&&!state.inventory.includes(c.requiresItemId)} className="rounded-2xl bg-white/10 p-5 text-left font-bold transition hover:bg-white hover:text-[#10261b] disabled:cursor-not-allowed disabled:opacity-40">{c.text}</button>)}</div></>}</div></section></div></main>
}
